# Generated by Django 2.2.4 on 2019-08-29 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190830_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
